### ISSUE TITLE
Document `templateName` and Blaze compatibility in the README

### ISSUE THREAD

**Issue by benjamn** [reactjs/react-meteor#45]
See #44 for past discussion.

In short, if you give your React component a `templateName: "Something"` property, then you can include that component in a Blaze template using the usual `{{> Something }}` syntax.

**Comment by ChadMartinson** [comment]
Blaze is returning "No such template Leaderboard". The error is in lookup.js 122

**Comment by benjamn** [comment]
You're probably using an older version of `reactjs:react` (current version is 0.2.1).

**Comment by ChadMartinson** [comment]
All I did was run meteor in this repo. I'll try updating it.

**Comment by ChadMartinson** [comment]
That worked thanks.

**Comment by benjamn** [comment]
Thanks for checking, and glad that's all it was :)

**Comment by ChadMartinson** [comment]
Give me a minute. I will do a pull request with all the examples updated.

Chad Martinson
704-519-7243

**Comment by ciwolsey** [comment]
I'm having a similar problem. I'm using 0.2.1, I have templateName: "hello", and I'm inserting using {{>hello}} and I get: "Uncaught Error: No such template: hello" on line 122 of lookup.js. Meteor version is 1.0.5. This

**Comment by liamzebedee** [comment]
I'm still getting this error - would anyone be able to help? 
Cheers.

**Comment by jazzdrive3** [comment]
Still getting this error myself. Using version 0.2.3.

**Comment by liamzebedee** [comment]
@jazzdrive3 I can't remember the specifics, but I've fixed it, and I needed to rename both the component and its variable name to be the same as `templateName`.

**Comment by jazzdrive3** [comment]
Component name and variable is the same as my templateName. Still getting the same error, "no such template."

**Comment by IonutLaceanu** [comment]
For me, it works only when I use `ReactMeteor.createClass`. 
If, instead of that, I use `React.createClass` + `mixins: [ReactMeteor.Mixin]`, I get the same error.

**Comment by noresjo** [comment]
I have the same experience as @IonutLaceanu . I don't know if that is a bug but I think the documentation could be clearer on this.

**Comment by smartdemocracy** [comment]
I noticed that using the package as dependence, the installed version is 0.1.2. After removing the dependence; add the package normally and updated meteor (`meteor update`), everything worked normally and now used version is 0.2.4

**Comment by antoniopresto** [comment]
Today I used the package as dependence, the installed version is 0.1.2, even the latest version being 0.2.4; so I got the same error. After using `api.use (['reactjs: react@0.2.4']);` everything worked normally. Try `meteor update` too.
